"use client";

import { Children, isValidElement, useEffect, useId, useState, type ReactNode, type ReactElement } from 'react';
import { LayoutDashboard, Boxes, SlidersHorizontal, Image, BadgeDollarSign, Tags, UsersRound, ClipboardList, ReceiptText, Printer, ChartNoAxesCombined, Store, LifeBuoy, MessageCircle, Settings2, Sparkles, type LucideIcon } from 'lucide-react';
const icons:Record<string,LucideIcon>={overview:LayoutDashboard,catalog:Boxes,editor:SlidersHorizontal,photo:Image,pricing:BadgeDollarSign,options:Tags,people:UsersRound,orders:ClipboardList,receipts:ReceiptText,printer:Printer,reports:ChartNoAxesCombined,store:Store,help:LifeBuoy,messages:MessageCircle,settings:Settings2,ai:Sparkles};
type SectionProps={id:string;title:string;icon?:string;children:ReactNode};
export function WorkspaceSection({children}:SectionProps){return <>{children}</>}
export function Workspace({children,label='Page sections',value,onValueChange,initialValue,hash=false}: {children:ReactNode;label?:string;value?:string;onValueChange?:(id:string)=>void;initialValue?:string;hash?:boolean}){
 const sections=Children.toArray(children).filter((child):child is ReactElement<SectionProps>=>isValidElement<SectionProps>(child)&&child.type===WorkspaceSection);
 const [current,setCurrent]=useState(initialValue||sections[0]?.props.id||'');const uid=useId();
 const selected=sections.some(section=>section.props.id===(value??current))?value??current:sections[0]?.props.id;
 const select=(id:string)=>{setCurrent(id);onValueChange?.(id);if(hash)history.replaceState(null,'',`#${id}`)};
 const sectionIds=sections.map(section=>section.props.id).join('|');
 useEffect(()=>{if(!hash)return;const sync=()=>{let id=location.hash.slice(1);try{id=decodeURIComponent(id)}catch{return}if(sectionIds.split('|').includes(id)){setCurrent(id);onValueChange?.(id)}};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[hash,sectionIds,onValueChange]);
 const SelectedIcon=icons[sections.find(section=>section.props.id===selected)?.props.icon||'overview']||LayoutDashboard;
 return <div className="workspace"><div className="workspace-navigation"><div className="workspace-mobile-picker"><SelectedIcon size={20} strokeWidth={1.8}/><label className="sr-only" htmlFor={`${uid}-select`}>{label}</label><select id={`${uid}-select`} value={selected} onChange={event=>select(event.target.value)}>{sections.map(section=><option value={section.props.id} key={section.props.id}>{section.props.title}</option>)}</select><span>{sections.findIndex(section=>section.props.id===selected)+1}/{sections.length}</span></div><div className="workspace-tabs" role="tablist" aria-label={label}>{sections.map((section,index)=>{const Icon=icons[section.props.icon||'overview']||LayoutDashboard;return <button type="button" key={section.props.id} role="tab" id={`${uid}-tab-${section.props.id}`} aria-controls={`${uid}-panel-${section.props.id}`} aria-selected={selected===section.props.id} tabIndex={selected===section.props.id?0:-1} onClick={()=>select(section.props.id)} onKeyDown={event=>{let target=index;if(event.key==='ArrowRight')target=(index+1)%sections.length;else if(event.key==='ArrowLeft')target=(index-1+sections.length)%sections.length;else if(event.key==='Home')target=0;else if(event.key==='End')target=sections.length-1;else return;event.preventDefault();select(sections[target].props.id);document.getElementById(`${uid}-tab-${sections[target].props.id}`)?.focus()}}><Icon size={18} strokeWidth={1.8}/>{section.props.title}</button>})}</div></div>{sections.map(section=><section key={section.props.id} id={`${uid}-panel-${section.props.id}`} role="tabpanel" aria-labelledby={`${uid}-tab-${section.props.id}`} className="workspace-content" hidden={selected!==section.props.id}>{section.props.children}</section>)}</div>
}
