import { getPlanConfig } from "@/lib/plan-gating";

export const marketingFeatures = [
  { slug: "pos", name: "POS System", title: "Checkout that keeps your day moving.", description: "Build a cart, choose a payment method, and keep a record of each sale in Caribbean POS Connect.", image: "tablet.jpg", route: "/pos", steps: ["Choose products from your catalog.", "Review quantities, customer details, and payment method.", "Complete the sale and open the receipt."] },
  { slug: "online-orders", name: "Online Orders", title: "Your storefront, open for orders.", description: "Publish your catalog for customers to browse and order from their phone. Manage incoming orders in your back office.", image: "bread.jpg", route: "/orders", steps: ["Publish your storefront from business settings.", "Share your store link with customers.", "Review incoming orders and update their status."] },
  { slug: "whatsapp", name: "WhatsApp", title: "Keep customers in the conversation.", description: "Use your customer and order details to prepare WhatsApp updates. Review the message before sending it through your configured workflow.", image: "juice.jpg", route: "/settings#whatsapp", steps: ["Set your business WhatsApp details.", "Open an order and choose the WhatsApp action.", "Review the prepared message and send the update."] },
  { slug: "receipts", name: "Receipts", title: "A clear record of every order.", description: "Find saved receipts, check sale details, and print or share records from your business workspace.", image: "coffee.jpg", route: "/receipts", steps: ["Place an order or complete a POS sale.", "Open the saved receipt from the order or receipts list.", "Print or share the receipt with your customer."] },
  { slug: "inventory", name: "Inventory", title: "Know what is ready to sell.", description: "Manage products, prices, categories, and stock quantities in one catalog with low-stock visibility.", image: "coffee.jpg", route: "/inventory", steps: ["Add products with photos, prices, and categories.", "Set stock quantities and reorder levels.", "Review low-stock items and keep your catalog current."] },
  { slug: "orders", name: "Orders", title: "From new order to completed sale.", description: "Review POS and storefront orders with customer details, payment method, and fulfillment information together.", image: "chicken.jpg", route: "/orders", steps: ["Review new orders in your workspace.", "Check the customer, payment, and fulfillment details.", "Update order status as your team completes the work."] },
  { slug: "customers", name: "Customers", title: "Remember the people behind each sale.", description: "Keep contact information and customer order records organized for your team.", image: "tablet.jpg", route: "/customers", steps: ["Create or find a customer profile.", "Save contact and delivery details.", "Review their order history or start a WhatsApp conversation."] },
  { slug: "reports", name: "Reports", title: "See how your business is doing.", description: "Review sales, payment methods, and product performance using the records from your business.", image: "tablet.jpg", route: "/reports", steps: ["Open your business reports.", "Review sales and payment breakdowns.", "Use product performance to plan your next stock order."] },
  { slug: "restaurants", name: "Restaurants", title: "Keep service and orders together.", description: "Manage your food catalog, counter sales, pickup orders, and delivery details from a shared workspace.", image: "chicken.jpg", route: "/pos", steps: ["Set up your menu and prices.", "Take counter or online orders.", "Track fulfillment and issue receipts."] },
  { slug: "retail", name: "Retail", title: "Your shop, from shelf to sale.", description: "Bring product management, checkout, customer records, and reports together for everyday retail.", image: "coffee.jpg", route: "/inventory", steps: ["Organize products and categories.", "Sell from the counter or your storefront.", "Review stock and sales in your dashboard."] },
  { slug: "cafes", name: "Cafes", title: "Make every coffee run a little smoother.", description: "Keep drinks, food, orders, and receipts organized so your team can focus on service.", image: "bread.jpg", route: "/pos", steps: ["Create your food and drinks catalog.", "Take orders and choose payment methods.", "Keep customer receipts and sales records together."] },
  { slug: "delivery", name: "Delivery teams", title: "From the order to the customer's door.", description: "Use saved delivery details to prepare the trip, open the destination in Waze, and update delivery status in your workspace.", image: "tablet.jpg", route: "/deliveries", steps: ["Review the customer's delivery address or coordinates.", "Open the saved destination in Waze.", "Update delivery status as the order progresses."] }
] as const;

const planDescriptions = [
  { id: "starter", name: "Starter", label: "Launch", detail: "For new businesses that need POS, products, orders, and receipts.", features: ["POS", "Products", "Orders", "Receipts"], highlighted: false },
  { id: "business", name: "Business", label: "Popular", detail: "For active teams that need storefront, staff tools, and messaging workflows.", features: ["Storefront", "Staff", "Messaging", "Reports"], highlighted: true },
  { id: "pro", name: "Pro", label: "Growth", detail: "For growing operations that need automation, reports, AI support, and scale.", features: ["Automation", "Analytics", "AI Support", "Multi-location"], highlighted: false }
] as const;

export const marketingPlans = planDescriptions.map((plan) => ({ ...plan, price: getPlanConfig(plan.id).monthlyPrice }));

export function publicPlanId(value: unknown) {
  return typeof value === "string" && marketingPlans.some((plan) => plan.id === value) ? value : null;
}
