import assert from "node:assert/strict";
import { SignJWT } from "jose";
import { NextRequest } from "next/server";
import { signSession, verifySession, sessionSecretKey } from "../lib/session";
import { middleware } from "../middleware";
import { readBoundedJson, unsafeRequestReason } from "../lib/request-security";
import { createLogoBuffer, trustedReceiptLogoUrl } from "../lib/receipt-logo";
import { deleteProductImageFromStorage, validProductImageBytes } from "../lib/supabase-storage";
import { businessSignupSchema, staffUserSchema } from "../lib/validators";
import { fail } from "../lib/api";

async function main() {
  Object.assign(process.env, { NODE_ENV: "production", SESSION_SECRET: "test-security-key-with-at-least-32-bytes", NEXT_PUBLIC_APP_URL: "https://pos.example", SUPABASE_URL: "https://storage.example", SUPABASE_SERVICE_ROLE_KEY: "test-only", SUPABASE_STORAGE_BUCKET: "product-images" });
  const secret = process.env.SESSION_SECRET;
  delete process.env.SESSION_SECRET;
  assert.throws(sessionSecretKey, /strong SESSION_SECRET/);
  process.env.SESSION_SECRET = "short";
  assert.throws(sessionSecretKey, /strong SESSION_SECRET/);
  process.env.SESSION_SECRET = secret;
  const token = await signSession("user-test");
  assert.equal(await verifySession(token), "user-test");
  await assert.rejects(() => verifySession(`${token.slice(0, -8)}forgedxx`));
  const legacy = await new SignJWT({ sub: "user-test" }).setProtectedHeader({ alg: "HS256" }).setIssuedAt().setExpirationTime("1h").sign(sessionSecretKey());
  await assert.rejects(() => verifySession(legacy));
  const expired = await new SignJWT({ sub: "user-test" }).setProtectedHeader({ alg: "HS256" }).setIssuer("caribbean-pos-connect").setAudience("cpc-session").setIssuedAt().setExpirationTime(1).sign(sessionSecretKey());
  await assert.rejects(() => verifySession(expired));
  const protectedResponse = await middleware(new NextRequest("https://pos.example/dashboard", { headers: { cookie: "cpc_session=forged" } }));
  assert.equal(protectedResponse.status, 307);
  assert.equal(new URL(protectedResponse.headers.get("location")!).pathname, "/login");
  assert.equal((await middleware(new NextRequest("https://pos.example/dashboard", { headers: { cookie: `cpc_session=${token}` } }))).status, 200);
  assert.equal((await middleware(new NextRequest("https://pos.example/login-private"))).status, 307);
  const request = (path: string, origin?: string) => new Request(`https://pos.example${path}`, { method: "POST", headers: origin ? { origin } : {} });
  assert.equal(unsafeRequestReason(request("/api/auth/login", "https://pos.example")), null);
  assert.ok(unsafeRequestReason(request("/api/auth/login", "https://attacker.example")));
  assert.ok(unsafeRequestReason(request("/api/auth/login", "null")));
  assert.equal(unsafeRequestReason(request("/api/paypal/webhook", "https://paypal.example")), null);
  assert.equal(unsafeRequestReason(request("/api/paypal/webhook/other", "https://paypal.example")), "Cross-site requests are not allowed.");
  assert.equal((await middleware(new NextRequest("https://pos.example/api/auth/login", { method: "POST", headers: { origin: "https://evil.example" } }))).status, 403);
  assert.equal((await middleware(new NextRequest("https://pos.example/api/test", { method: "POST", headers: { "content-length": "9000000" } }))).status, 413);
  assert.deepEqual(await readBoundedJson(new Request("https://pos.example", { method: "POST", body: '{"ok":true}' })), { ok: true });
  assert.equal(await readBoundedJson(new Request("https://pos.example", { method: "POST", body: '"' + 'a'.repeat(20) + '"' }), 10), null);
  assert.equal(await readBoundedJson(new Request("https://pos.example", { method: "POST", body: "{" })), null);
  for (const value of ["http://127.0.0.1/logo.png", "https://attacker.example/logo.png", "https://storage.example.attacker.example/logo.png", "https://user:pass@storage.example/logo.png", "https://storage.example:444/logo.png"]) assert.equal(trustedReceiptLogoUrl(value), null);
  assert.equal(trustedReceiptLogoUrl("https://storage.example/logo.png")?.hostname, "storage.example");
  assert.equal(await createLogoBuffer("/../package.json.png"), null);
  const fetchBefore = globalThis.fetch;
  let calls = 0;
  globalThis.fetch = async () => { calls++; return new Response("", { status: 200 }); };
  try {
    assert.equal(await createLogoBuffer("http://169.254.169.254/latest/meta-data"), null);
    assert.equal(await createLogoBuffer("https://evil.example/logo.png"), null);
    const foreign = await deleteProductImageFromStorage("https://storage.example/storage/v1/object/public/product-images/businesses/tenant-b/products/product-b/photo.png", { businessId: "tenant-a", productId: "product-a" });
    assert.equal(foreign.deleted, false);
    assert.equal(calls, 0);
    await deleteProductImageFromStorage("https://storage.example/storage/v1/object/public/product-images/businesses/tenant-a/products/product-a/photo.png", { businessId: "tenant-a", productId: "product-a" });
    assert.equal(calls, 1);
    let options: RequestInit | undefined;
    globalThis.fetch = async (_url, init) => { options = init; return new Response(new Uint8Array(1), { headers: { "content-type": "image/png", "content-length": String(3 * 1024 * 1024) } }); };
    assert.equal(await createLogoBuffer("https://storage.example/large.png"), null);
    assert.equal(options?.redirect, "error");
    globalThis.fetch = async () => new Response(new Uint8Array(3 * 1024 * 1024), { headers: { "content-type": "image/png" } });
    assert.equal(await createLogoBuffer("https://storage.example/chunked.png"), null);
  } finally { globalThis.fetch = fetchBefore; }
  assert.equal(validProductImageBytes(new TextEncoder().encode("<script>bad</script>").buffer, "image/png"), false);
  assert.equal(validProductImageBytes(new Uint8Array([137,80,78,71,13,10,26,10]).buffer, "image/png"), true);
  assert.equal(staffUserSchema.safeParse({ name: "Staff", email: "staff@example.com", role: "cashier", password: "ChangeMe123!" }).success, false);
  assert.equal(businessSignupSchema.safeParse({ business_name: "Shop", email: "owner@example.com", whatsapp_number: "18681234567", password: "a".repeat(73) }).success, false);
  const response = fail("Database request failed: private query", 500, { host: "private" });
  const payload = await response.json();
  assert.ok(!JSON.stringify(payload).includes("private"));
  console.log("Security regression checks passed: session forgery/expiry/secrets, route boundaries, cross-site requests, bounded JSON, logo fetches, tenant image deletion, image signatures, passwords, and error redaction.");
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
