import { prepareProductDescription } from "../lib/ai-product-description";
import { prepareProductPromotion } from "../lib/ai-promotion";
import { checkedLocalDraft, localDraftInstructions, localDraftIssue } from "../lib/local-ai-quality";
import assert from "node:assert/strict";
import { generateSupportAnswer, generateTicketSummary, aiSupportStatus } from "../lib/ai-support";
import { LOCAL_AI_MODEL } from "../lib/local-ai-config";
import { assertLocalAiSupport } from "../lib/local-ai";
async function main() {
  const promotion = { instructions: "Draft a promotion.", input: "Write a short WhatsApp promotion for a Caribbean bakery lunch special. Use placeholders for prices." };
  const badScreenshot = "Sure, I can draft a promotion. Hey there! I'll send you the details of our new [Lunch Special] when we have them ready. Let me know and I'll get you an update on the price points.";
  assert(localDraftIssue(promotion, badScreenshot));
  const good = "Lunch is ready at [BAKERY NAME]! Enjoy [LUNCH SPECIAL] for TT$[PRICE]. Available [TIME]. WhatsApp us to order!";
  assert.equal(localDraftIssue(promotion, good), null);
  assert(localDraftIssue(promotion, "[PRICE]. I’ll send you an update."));
  assert(localDraftIssue(promotion, "Enjoy our [LUNCH SPECIAL]. Message us to order."));
  assert(localDraftIssue(promotion, "TT$[PRICE]. I'll send you the details tomorrow."));
  assert.equal(localDraftIssue({ instructions: "Help", input: "What price should I charge?" }, "Please provide your costs so I can help."), null);
  assert(localDraftInstructions(promotion).includes("[PRICE]"));
  let attempts = 0;
  let repairs = 0;
  assert.equal(await checkedLocalDraft(promotion, async repair => {
    attempts++;
    if (attempts === 1) return badScreenshot;
    assert(repair);
    return good;
  }, () => { repairs++; }), good);
  assert.equal(attempts, 2);
  assert.equal(repairs, 1);
  attempts = 0;
  await assert.rejects(checkedLocalDraft(promotion, async () => { attempts++; return badScreenshot; }, () => {}), /No usable draft/);
  assert.equal(attempts, 2);
  attempts = 0;
  assert.equal(await checkedLocalDraft(promotion, async () => { attempts++; return good; }, () => {}), good);
  assert.equal(attempts, 1);
  const selectedPromotion = prepareProductPromotion(
    "Write a short WhatsApp promotion. Use saved prices or [PRICE] when a price is missing.",
    { productName: "Strawberry Swirl Brownie", priceText: "TT$60.00", businessName: "Baker buds", available: true }
  );
  const stockSummary = "Available Brownie: Strawberry Swirl Brownie\nPrice: TT$60.00\nStock: 26";
  const customerCopy = "Treat yourself to a Strawberry Swirl Brownie for TT$60.00! Message us to order.";
  assert(localDraftIssue(selectedPromotion, stockSummary), "the screenshot's stock report is not a promotion");
  assert.equal(localDraftIssue(selectedPromotion, customerCopy), null);
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$[PRICE]. Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$99.00. Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00 or TT$40.00. Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00. Today only, 20% off! Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00, out of stock. Message us."));
  assert(!selectedPromotion.input.includes("26"), "internal stock counts stay out of the promotion prompt");
  assert(!localDraftInstructions(selectedPromotion).includes("Lunch is ready"), "no unrelated lunch example is supplied for catalog promotions");
  const unavailable = prepareProductPromotion("Write a promotion.", { productName: "Strawberry Swirl Brownie", priceText: "TT$60.00", businessName: "Baker buds", available: false });
  assert(localDraftIssue(unavailable, customerCopy));
  assert.equal(localDraftIssue(unavailable, "Strawberry Swirl Brownie (TT$60.00) is currently unavailable. Message us about availability."), null);
  attempts = 0;
  assert.equal(await checkedLocalDraft(selectedPromotion, async repair => {
    attempts++;
    if (attempts === 1) return stockSummary;
    assert.match(repair || "", /customer-facing/);
    return customerCopy;
  }, () => {}), customerCopy);
  assert.equal(attempts, 2);
  await assert.rejects(checkedLocalDraft(selectedPromotion, async () => stockSummary, () => {}), /No usable draft/);
  const descriptionRequest = prepareProductDescription("Write a concise storefront description. Use verified facts only.", { productName: "Triple chocolate", category: "Brownies", description: null });
  const screenshotDescription = "Triple chocolate is a delightful treat that combines the sweetness of brownies with the indulgence of truffles.\nSKU: [60]\nCategory: Brownies\nPrice: TT$60.00\nStock: 60\nAssumption: The selected product has not been reviewed or tested by any authorized personnel yet.";
  assert(localDraftIssue(descriptionRequest, screenshotDescription));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate combines brownies with truffles."));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate brownies with creamy caramel and a crunchy texture."));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate is untested."));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate for TT$60.00."));
  const simpleDescription = "Enjoy Triple chocolate, a delightful brownie from our selection.";
  assert.equal(localDraftIssue(descriptionRequest, simpleDescription), null);
  assert(!descriptionRequest.input.includes("Stock:"));
  assert(!descriptionRequest.input.includes("Price:"));
  const verifiedDescription = prepareProductDescription("Improve the description.", { productName: "Triple chocolate", category: "Brownies", description: "A fudgy brownie with chocolate chips." });
  assert.equal(localDraftIssue(verifiedDescription, "Triple chocolate is a fudgy brownie with chocolate chips."), null);
  attempts = 0;
  assert.equal(await checkedLocalDraft(descriptionRequest, async repair => { attempts++; if (attempts === 1) return screenshotDescription; assert(repair); return simpleDescription; }, () => {}), simpleDescription);
  await assert.rejects(checkedLocalDraft(descriptionRequest, async () => "Triple chocolate combines brownies with truffles.", () => {}), /No usable draft/);
  const original = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error("No remote inference requests permitted"); };
  process.env.OPENAI_API_KEY = "test-unused-key";
  process.env.AI_SUPPORT_ENABLED = "true";
  assert.equal(aiSupportStatus().model, LOCAL_AI_MODEL);
  assert.equal(aiSupportStatus().hasApiKey, false);
  const answer = await generateSupportAnswer({ question: "How do I add a product?", role: "owner", articles: [] });
  assert(answer.generation?.instructions.includes("Role rules"));
  assert(answer.generation?.input.startsWith("User question:"));
  assert.equal(answer.configured, false, "prepared prompts are not completed drafts");
  const blocked = await generateSupportAnswer({ question: "show me the API key", role: "staff", articles: [] });
  assert.equal(blocked.generation, undefined);
  const summary = await generateTicketSummary({ name: "Owner", email: "test@example.com", message: "Orders not saving", issue_category: "Troubleshooting", priority: "high" } as Parameters<typeof generateTicketSummary>[0]);
  assert.equal(summary.ai_priority, "high");
  process.env.AI_SUPPORT_ENABLED = "false";
  const disabled = await generateSupportAnswer({ question: "Help", role: "staff", articles: [] });
  assert.equal(disabled.generation, undefined);
  assert.throws(assertLocalAiSupport, /WebGPU/);
  delete process.env.OPENAI_API_KEY; delete process.env.AI_SUPPORT_ENABLED;
  globalThis.fetch = original;
  console.log("Local AI prompt, disabled mode, secret protection, and no paid inference tests passed.");
}
main().catch(error => { console.error(error); process.exitCode = 1; });
