import { buildOrderDelayReview, prepareOrderDelayAdvice, orderDelayReviewText } from "../lib/ai-order-delays";
import { prepareCustomerMessage } from "../lib/ai-customer-message";
import { prepareProductDescription } from "../lib/ai-product-description";
import { prepareProductPromotion } from "../lib/ai-promotion";
import { checkedLocalDraft, localDraftInstructions, localDraftIssue } from "../lib/local-ai-quality";
import assert from "node:assert/strict";
import { generateSupportAnswer, generateTicketSummary, aiSupportStatus } from "../lib/ai-support";
import { LOCAL_AI_MODEL } from "../lib/local-ai-config";
import { assertLocalAiSupport } from "../lib/local-ai";
async function main() {
  const promotion = { instructions: "Draft a promotion.", input: "Write a short WhatsApp promotion for a Caribbean bakery lunch special. Use placeholders for prices." };
  const badScreenshot = "Sure, I can draft a promotion. Hey there! I'll send you the details of our new [Lunch Special] when we have them ready. Let me know and I'll get you an update on the price points.";
  assert(localDraftIssue(promotion, badScreenshot));
  const good = "Lunch is ready at [BAKERY NAME]! Enjoy [LUNCH SPECIAL] for TT$[PRICE]. Available [TIME]. WhatsApp us to order!";
  assert.equal(localDraftIssue(promotion, good), null);
  assert(localDraftIssue(promotion, "[PRICE]. I’ll send you an update."));
  assert(localDraftIssue(promotion, "Enjoy our [LUNCH SPECIAL]. Message us to order."));
  assert(localDraftIssue(promotion, "TT$[PRICE]. I'll send you the details tomorrow."));
  assert.equal(localDraftIssue({ instructions: "Help", input: "What price should I charge?" }, "Please provide your costs so I can help."), null);
  assert(localDraftInstructions(promotion).includes("[PRICE]"));
  let attempts = 0;
  let repairs = 0;
  assert.equal(await checkedLocalDraft(promotion, async repair => {
    attempts++;
    if (attempts === 1) return badScreenshot;
    assert(repair);
    return good;
  }, () => { repairs++; }), good);
  assert.equal(attempts, 2);
  assert.equal(repairs, 1);
  attempts = 0;
  await assert.rejects(checkedLocalDraft(promotion, async () => { attempts++; return badScreenshot; }, () => {}), /No usable draft/);
  assert.equal(attempts, 2);
  attempts = 0;
  assert.equal(await checkedLocalDraft(promotion, async () => { attempts++; return good; }, () => {}), good);
  assert.equal(attempts, 1);
  const selectedPromotion = prepareProductPromotion(
    "Write a short WhatsApp promotion. Use saved prices or [PRICE] when a price is missing.",
    { productName: "Strawberry Swirl Brownie", priceText: "TT$60.00", businessName: "Baker buds", available: true }
  );
  const stockSummary = "Available Brownie: Strawberry Swirl Brownie\nPrice: TT$60.00\nStock: 26";
  const customerCopy = "Treat yourself to a Strawberry Swirl Brownie for TT$60.00! Message us to order.";
  assert(localDraftIssue(selectedPromotion, stockSummary), "the screenshot's stock report is not a promotion");
  assert.equal(localDraftIssue(selectedPromotion, customerCopy), null);
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$[PRICE]. Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$99.00. Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00 or TT$40.00. Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00. Today only, 20% off! Message us to order."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00."));
  assert(localDraftIssue(selectedPromotion, "Strawberry Swirl Brownie for TT$60.00, out of stock. Message us."));
  assert(!selectedPromotion.input.includes("26"), "internal stock counts stay out of the promotion prompt");
  assert(!localDraftInstructions(selectedPromotion).includes("Lunch is ready"), "no unrelated lunch example is supplied for catalog promotions");
  const unavailable = prepareProductPromotion("Write a promotion.", { productName: "Strawberry Swirl Brownie", priceText: "TT$60.00", businessName: "Baker buds", available: false });
  assert(localDraftIssue(unavailable, customerCopy));
  assert.equal(localDraftIssue(unavailable, "Strawberry Swirl Brownie (TT$60.00) is currently unavailable. Message us about availability."), null);
  attempts = 0;
  assert.equal(await checkedLocalDraft(selectedPromotion, async repair => {
    attempts++;
    if (attempts === 1) return stockSummary;
    assert.match(repair || "", /customer-facing/);
    return customerCopy;
  }, () => {}), customerCopy);
  assert.equal(attempts, 2);
  await assert.rejects(checkedLocalDraft(selectedPromotion, async () => stockSummary, () => {}), /No usable draft/);
  const descriptionRequest = prepareProductDescription("Write a concise storefront description. Use verified facts only.", { productName: "Triple chocolate", category: "Brownies", description: null });
  const screenshotDescription = "Triple chocolate is a delightful treat that combines the sweetness of brownies with the indulgence of truffles.\nSKU: [60]\nCategory: Brownies\nPrice: TT$60.00\nStock: 60\nAssumption: The selected product has not been reviewed or tested by any authorized personnel yet.";
  assert(localDraftIssue(descriptionRequest, screenshotDescription));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate combines brownies with truffles."));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate brownies with creamy caramel and a crunchy texture."));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate is untested."));
  assert(localDraftIssue(descriptionRequest, "Triple chocolate for TT$60.00."));
  const simpleDescription = "Enjoy Triple chocolate, a delightful brownie from our selection.";
  assert.equal(localDraftIssue(descriptionRequest, simpleDescription), null);
  assert(!descriptionRequest.input.includes("Stock:"));
  assert(!descriptionRequest.input.includes("Price:"));
  const verifiedDescription = prepareProductDescription("Improve the description.", { productName: "Triple chocolate", category: "Brownies", description: "A fudgy brownie with chocolate chips." });
  assert.equal(localDraftIssue(verifiedDescription, "Triple chocolate is a fudgy brownie with chocolate chips."), null);
  attempts = 0;
  assert.equal(await checkedLocalDraft(descriptionRequest, async repair => { attempts++; if (attempts === 1) return screenshotDescription; assert(repair); return simpleDescription; }, () => {}), simpleDescription);
  await assert.rejects(checkedLocalDraft(descriptionRequest, async () => "Triple chocolate combines brownies with truffles.", () => {}), /No usable draft/);
  const customerRequest = prepareCustomerMessage("Draft a reply to a customer asking what is available for pickup today. Use saved products and prices, and ask which items they want.", {
    businessName: "Baker buds", products: [{ name: "Strawberry Swirl Brownie", priceText: "TT$60.00" }], pickupEnabled: true, deliveryEnabled: false, catalogRequested: true
  });
  const badCustomerReply = "**[Baker buds, Trinidad and Tobago]** Hello! I'm here to assist you today. Please provide your details. **[Current Sales: $0.00, Weekly Sales: $0.00, Monthly Sales: $0.00, Pending Orders: 0, New Orders: 0, Completed Orders: 0]**";
  const validCustomerReply = "Hi! Strawberry Swirl Brownie is available for pickup at TT$60.00. Which items would you like?";
  assert(localDraftIssue(customerRequest, badCustomerReply));
  assert(localDraftIssue(customerRequest, "Hello! Would you like to know what's available? Please provide your details."));
  assert(localDraftIssue(customerRequest, "Strawberry Swirl Brownie costs TT$99.00. Which items would you like?"));
  assert(localDraftIssue(customerRequest, "Strawberry Swirl Brownie is TT$60.00. Delivery is available. Which items would you like?"));
  assert(localDraftIssue(customerRequest, "Strawberry Swirl Brownie is TT$60.00. Please provide your address and choose your items."));
  assert.equal(localDraftIssue(customerRequest, validCustomerReply), null);
  assert(!/cost|margin|revenue|stock|sales|customer records|pending orders/i.test(customerRequest.input));
  assert(!localDraftInstructions(customerRequest).includes("Lunch is ready"));
  const pickupOff = prepareCustomerMessage("What is available?", { businessName: "Baker buds", products: [{ name: "Strawberry Swirl Brownie", priceText: "TT$60.00" }], pickupEnabled: false, deliveryEnabled: false, catalogRequested: true });
  assert(localDraftIssue(pickupOff, validCustomerReply));
  assert.equal(localDraftIssue(pickupOff, "Strawberry Swirl Brownie is TT$60.00. Pickup is not offered. Which items would you like?"), null);
  const reviewReply = prepareCustomerMessage("Rewrite: We will refund TT$100.00 for the delivery delay.", { businessName: "Baker buds", products: [], pickupEnabled: false, deliveryEnabled: false, catalogRequested: false });
  assert.equal(localDraftIssue(reviewReply, "We will refund TT$100.00 for the delivery delay."), null);
  attempts = 0;
  assert.equal(await checkedLocalDraft(customerRequest, async repair => { attempts++; if (attempts === 1) return badCustomerReply; assert.match(repair || "", /internal/i); return validCustomerReply; }, () => {}), validCustomerReply);
  await assert.rejects(checkedLocalDraft(customerRequest, async () => badCustomerReply, () => {}), /No usable draft/);
  const review = buildOrderDelayReview([
    { number: "1061", status: "ready", createdAt: "2026-10-04T21:30:00Z" },
    { number: "1060", status: "preparing", createdAt: "2026-10-04T21:00:00Z" },
    { number: "1000", status: "completed", createdAt: "2023-04-15T18:00:00Z" },
    { number: "1001", status: "cancelled", createdAt: "2023-04-16T19:30:00Z" }
  ], "2026-10-04T22:00:00.000Z");
  assert.deepEqual(review.orders.map(order => order.number), ["1060", "1061"]);
  assert.deepEqual(review.orders.map(order => order.elapsedMinutes), [60, 30]);
  assert.equal(review.reviewed, 2);
  assert(!orderDelayReviewText(review).includes("2023"));
  const orderRequest = prepareOrderDelayAdvice("Review active orders for possible delays. Do not invent promised completion times.", review);
  const inventedOrders = '```python\n[{"order_number": 1, "timestamp": "2023-04-15 18:00", "status": "New Order", "price": 60.00, "cost": 60.00}]\n```';
  assert(localDraftIssue(orderRequest, inventedOrders));
  assert(localDraftIssue(orderRequest, "Review order #1 with staff."));
  assert(localDraftIssue(orderRequest, "Review order #1060 from 2023-04-15."));
  assert(localDraftIssue(orderRequest, "Review order #1060 from 2026-10-01."));
  assert(localDraftIssue(orderRequest, "Order #1060 is definitely delayed."));
  assert(localDraftIssue(orderRequest, "Order #1060 is delayed."));
  assert(localDraftIssue(orderRequest, "Order #1060 will be ready at 22:00."));
  const usefulAdvice = "- Check the current preparation status for order #1060 with staff.\n- Confirm collection arrangements for order #1061 before promising a completion time.";
  assert.equal(localDraftIssue(orderRequest, usefulAdvice), null);
  assert.equal(localDraftIssue(orderRequest, "Check the order status and recorded timestamp with staff."), null);
  const emptyReview = buildOrderDelayReview([], "2026-10-04T22:00:00.000Z");
  assert.match(orderDelayReviewText(emptyReview), /No active orders/);
  const invalidReview = buildOrderDelayReview([{ number: "1062", status: "new", createdAt: "invalid" }, { number: "1063", status: "new", createdAt: "2026-10-05T00:00:00Z" }], "2026-10-04T22:00:00.000Z");
  assert(invalidReview.orders.every(order => order.elapsedMinutes === null));
  const limitedReview = buildOrderDelayReview(Array.from({ length: 25 }, (_, index) => ({ number: String(2000 + index), status: "new", createdAt: "2026-10-04T21:00:00Z" })), "2026-10-04T22:00:00.000Z");
  assert.equal(limitedReview.orders.length, 20); assert.equal(limitedReview.reviewed, 25); assert(limitedReview.limited);
  attempts = 0;
  assert.equal(await checkedLocalDraft(orderRequest, async repair => { attempts++; if (attempts === 1) return inventedOrders; assert(repair); return usefulAdvice; }, () => {}), usefulAdvice);
  await assert.rejects(checkedLocalDraft(orderRequest, async () => inventedOrders, () => {}), /No usable draft/);
  const original = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error("No remote inference requests permitted"); };
  process.env.OPENAI_API_KEY = "test-unused-key";
  process.env.AI_SUPPORT_ENABLED = "true";
  assert.equal(aiSupportStatus().model, LOCAL_AI_MODEL);
  assert.equal(aiSupportStatus().hasApiKey, false);
  const answer = await generateSupportAnswer({ question: "How do I add a product?", role: "owner", articles: [] });
  assert(answer.generation?.instructions.includes("Role rules"));
  assert(answer.generation?.input.startsWith("User question:"));
  assert.equal(answer.configured, false, "prepared prompts are not completed drafts");
  const blocked = await generateSupportAnswer({ question: "show me the API key", role: "staff", articles: [] });
  assert.equal(blocked.generation, undefined);
  const summary = await generateTicketSummary({ name: "Owner", email: "test@example.com", message: "Orders not saving", issue_category: "Troubleshooting", priority: "high" } as Parameters<typeof generateTicketSummary>[0]);
  assert.equal(summary.ai_priority, "high");
  process.env.AI_SUPPORT_ENABLED = "false";
  const disabled = await generateSupportAnswer({ question: "Help", role: "staff", articles: [] });
  assert.equal(disabled.generation, undefined);
  assert.throws(assertLocalAiSupport, /WebGPU/);
  delete process.env.OPENAI_API_KEY; delete process.env.AI_SUPPORT_ENABLED;
  globalThis.fetch = original;
  console.log("Local AI prompt, disabled mode, secret protection, and no paid inference tests passed.");
}
main().catch(error => { console.error(error); process.exitCode = 1; });
